### ISSUE TITLE
FR: add support for newly released NFT APIs

### ISSUE THREAD

**Issue by thebrianchen** [alchemyplatform/alchemy-sdk-js#140]
Tracking issue for several new NFT endpoints that need to be added into the SDK:

- [X] [computeRarity](https://docs.alchemy.com/reference/computerarity): Done in #148 
- [X] [searchContractMetadata](https://docs.alchemy.com/reference/searchcontractmetadata) Done in #163
- [X] [summarizeNFTAttributes](https://docs.alchemy.com/reference/summarizenftattributes) Done in #155 
- [X] [getNftSales](https://docs.alchemy.com/reference/getnftsales): Done in #190 
- [X] [reportSpamContract](https://docs.alchemy.com/reference/reportspamcontract) (Not relevant to SDK)
- [X] [getNftMetadataBatch](https://docs.alchemy.com/reference/getnftmetadatabatch): Done in #189
- [X] [getContractsForOwner](https://docs.alchemy.com/reference/getcontractsforowner): Done in #201

**Comment by xeno097** [comment]
Hi, I'd like to work on some of those missing NFT endpoints. I'd start with the `computeRarity` one and then maybe implement the others. Are there any guidelines I should follow to implement the feature?

**Comment by thebrianchen** [comment]
@xeno097 Thanks for offering to help! I'll work on a more holistic contributing document in the coming weeks.

For the NFT APIs: 
- Add the top-level method into the `NftNamespace` and the underlying implementation in `src/internal/nft-api.ts`.
- Add unit tests in `test/unit/nft-api.test.ts`.
- Add a couple integration tests into `test/integration/nft.test.ts`.

Thanks! Just a heads up, we're working on changing the payloads in `getNftSales`, so some of the API surface area might change.

**Comment by xeno097** [comment]
Nice! I'll try to get something done over the weekend and keep an eye on the repo for the changes.

**Comment by xeno097** [comment]
@thebrianchen do you prefer that I keep working with smaller prs like the last one or a big one with everything? I'd prefer working with smaller ones because I think is tidier.

**Comment by thebrianchen** [comment]
Prefer smaller PRs as well! Easier to manage and review for sure.
